name: Deploy Development API

permissions:
  contents: read

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_run:
    workflows: ["Run Tests"]
    branches: [dev]
    types:
      - completed

env:
  HOST: root@chiligarlic.com
  IMAGE_NAME: dotagiftx/api:dev
  IMAGE_FILE: api.tar
  WORKDIR: ~/dotagiftx/dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: SSH Image Deploy
        run: |
          docker save -o $IMAGE_FILE $IMAGE_NAME
          scp $IMAGE_FILE $HOST:$WORKDIR/$IMAGE_FILE
          ssh $HOST "cd $WORKDIR && docker load -i $IMAGE_FILE && ./restart.sh"

#      - name: SSH Binary Upload
#        run: scp $BIN_FILE $HOST:$WORKDIR/$BIN_NAME
